ecommit_javascript:
    tiny_mce:
         #Chemin du fichier Javascript de TinyMCE
         script_url: js/tiny_mce/tiny_mce.js
    recaptcha:
         #Clé publique de Recaptcha
         public_key: CHANGE IT
         #Clé privée de Recaptcha
         private_key: CHANTE IT
         #Utilisation d'une connexion sécurisée
         secure: false
         #Active ou non Recaptcha
         enable: true
    #Utilise ou non bootstrap pour l'application (pour la creation des boutons)
    use_boostrap: false