ecommit_javascript:
    recaptcha:
         #Clé publique de Recaptcha
         public_key: CHANGE IT
         #Clé privée de Recaptcha
         private_key: CHANTE IT
         #Utilisation d'une connexion sécurisée
         secure: false
         #Active ou non Recaptcha
         enable: true
    #Utilise ou non bootstrap pour l'application (pour la creation des boutons)
    use_bootstrap: false
    #Service utilisé pour Overlay
    overlay_service: ecommit_javascript.overlay.jquery_popup_overlay
