ecommit_javascript:
    jQuery_core:
         #Ajoute (ou non) le fichier de jQuery à toutes les requetes
         auto_enable: false
         #Chemin du fichier JavaScript du core de jQuery
         js: ejs/jQuery/jquery.min.js
    jQuery_ui:
         #Chemin du fichier JavaScript de jQuery Ui
         js: ejs/jQuery/ui/js/jquery-ui.custom.min.js
         #Chemin du fichier CSS de jQuery Ui
         css: ejs/jQuery/ui/css/smoothness/jquery-ui.custom.css
    jQuery_tools:
         #Chemin du fichier JavaScript du plugin jQuery Tools
         js: ejs/jQuery/tools/jquery.tools.min.js
    ajax:
         #Ajoute automatiquement le traitement des erreurs dans les requetes Ajax
         autocallbacks: true
    tiny_mce:
         #Chemin du fichier Javascript de TinyMCE
         script_url: js/tiny_mce/tiny_mce.js
         #Chemin du fichier Javascript du plugin jQuery TinyMCE
         jQuery_script_url: js/tiny_mce/jquery.tinymce.js
    recaptcha:
         #Clé publique de Recaptcha
         public_key: CHANGE IT
         #Clé privée de Recaptcha
         private_key: CHANTE IT
         #Utilisation d'une connexion sécurisée
         secure: false
         #Active ou non Recaptcha
         enable: true